### ISSUE TITLE
crates.io documentation link incorrect

### ISSUE THREAD

**Issue by unknowndevice** [vhbit/lmdb-rs#12]
Should be https://vhbit.github.io/lmdb-rs/lmdb_rs/index.html but is set to https://vhbit.github.io/lmdb-rs/lmdb-rs

Reference: https://crates.io/crates/lmdb-rs

**Comment by vhbit** [comment]
See #11 - should be fixed now, probably you've got to window between push
and actual Travis build.

-- 
Sent from mobile

**Comment by vhbit** [comment]
@unknowndevice sorry, I've misread description, fixed documentation link for crates.io too.

**Comment by unknowndevice** [comment]
Thanks!
