### ISSUE TITLE
keyrange with excluding end

### ISSUE THREAD

**Issue by xitep** [vhbit/lmdb-rs#13]
Hello,

is there a nice way to iterate over keys starting with a given "from" key (including that) while ending the iteration at a given "end" key (this is, excluding that key from the iteration)? While `keyrange_from/_to` individually provide what I need, it seems that `keyrange` includes the "end" key on purpose. However, I fail to find a strong reason for this.

P.

**Comment by xitep** [comment]
Made a proposal with pull request [https://github.com/vhbit/lmdb-rs/pull/14] which I can imagine to co-exist with the current library without breaking backwards compatibility.

**Comment by vhbit** [comment]
Fixed by merging #14

**Comment by xitep** [comment]
Thank you!

**Comment by xitep** [comment]
Would it be possible to release this as a 4.0.1 on crates.io?

**Comment by vhbit** [comment]
@xitep sorry for delays - it's a bit busy time here. I want to do some more minor changes before pushing a new version, I'll try to find a time slice today to finish them.

**Comment by xitep** [comment]
many thanks! but there's no need to rush. it would be merely a convenience for me at this point in time. really, no need to rush.

**Comment by vhbit** [comment]
@xitep it seems with a new born it'll be much harder than I expected to land changes I've planned so I've just released 0.4.1 as it is, sorry again for a long wait.

**Comment by xitep** [comment]
:) Thank you!
