### ISSUE TITLE
Windows fixes

### ISSUE THREAD

**Issue by photex** [vhbit/lmdb-rs#37]
Howdy!

Once #36 is merged I'd like to submit a PR for this commit: https://github.com/photex/lmdb_rs/commit/de3056ce1abe605d747295f9b910085f54dbc484

Using msvc and rust 1.10 I can build and all tests pass. Haven't dug into it other than that.

**Comment by vhbit** [comment]
That's great! What I would like to see additionally to those changes is to update `.travis.yml` file to test it on Windows

**Comment by photex** [comment]
I'm not sure that travis supports windows. I didn't see a way to do this in their docs, but I'll look around a bit more.
I think most projects are using Appveyor for windows tests. I could look into that too if you're ok with that.

**Comment by vhbit** [comment]
Pull request was merged, feel free to create a new one for Windows.
Appveyor sounds good to me, I've setup project there and I hope with configuration file in pull request it'll start building automatically.
