### ISSUE TITLE
please publish a new version to crates.io

### ISSUE THREAD

**Issue by iqualfragile** [vhbit/lmdb-rs#44]
there is already a pull request, please press the merge button, currently this crate does not compile on crates.io (apparently a backwards incompatible compiler change)
https://github.com/vhbit/lmdb-rs/pull/43

**Comment by xitep** [comment]
merged #43; however, i do not have permissions to publish the crate on crates.io. we'll have to wait for @vhbit

**Comment by vhbit** [comment]
I'll publish it soon, but considering `cargo` allows to pinpoint dependency to commit, that shouldn't be a big problem at all.

**Comment by iqualfragile** [comment]
no, every single version i tested was broken, the compiler seemed to have an incompatible update, the crate is currently unusuable in any version, this is a big problem!

**Comment by vhbit** [comment]
The point is that `cargo` allows to pinpoint version to commit, which means you can write in `Cargo.toml` 

```
lmdb-rs = { git = "https://github.com/vhbit/lmdb-rs", rev = "18102ecf1441698eff49343d7500c22884d0a107" }
```

and it should work until new version is published.

**Comment by vhbit** [comment]
`0.7.5` was published earlier today.
