### ISSUE TITLE
Environment Sync?

### ISSUE THREAD

**Issue by ArtemGr** [vhbit/lmdb-rs#5]
I wonder if `core::Environment` is supposed to be thread-safe and should be marked as `Sync`?
It seems so from `db_cache: Mutex`. Also LMDB says that it's "thread-aware" and forbids opening the database twice ("Do not have open an LMDB database twice in the same process at the same time" - http://symas.com/mdb/doc/) so I gather the `MDB_env` should be thread-safe.

**Comment by vhbit** [comment]
Yep, it is, although Rust doesn't know that yet :smile: It requires a couple of changes, like also marking as `Send`, changing `db_cache` to `Arc<Mutex<_>>` and so on.

**Comment by ArtemGr** [comment]
Actually I don't need to move it around (with Arc), I'm using a singleton with the help of lazy_static, so I've added just the Sync (https://github.com/ArtemGr/lmdb-rs/commit/91446a8255ea27a63edc70c1087187af1164f246) and it seems to work.

**Comment by ArtemGr** [comment]
https://github.com/vhbit/lmdb-rs/pull/6
