### ISSUE TITLE
FYI, there seem to be a problem with `keyrange_to` with MDB_INTEGERKEY

### ISSUE THREAD

**Issue by ArtemGr** [vhbit/lmdb-rs#9]
Just FYI, I've encountered a persevering early termination problem iterating keys with `keyrange_to`.
With the database defined as follows:

    let expiration_idx = try! (env.create_db ("expiration_idx", DbFlags::from_bits_truncate (lmdb_sys::MDB_DUPSORT | lmdb_sys::MDB_INTEGERKEY)));

I had to rewrite the loop as follows:

      let mut hashes_found: Vec<u64> = Vec::new();  // NB: Must not change the index while iterating it.
      let till = time::get_time().sec as u64;
      // NB: Using `iter` because `keyrange_to` doesn't work as expected (misses some keys).
      for rec in try! (expiration_idx.iter()) {
        if rec.get_key::<u64>() > till {break}
        hashes_found.push (rec.get_value::<u64>());}

Because the `keyrange_to` version terminated early and have been missing some keys.

The problematic `keyrange_to` version:

      let till = time::get_time().sec as u64 + 1;
      for rec in try! (expiration_idx.keyrange_to (&till)) {
        hashes_found.push (rec.get_value::<u64>());}

**Comment by vhbit** [comment]
> The problematic |keyrange_to| version:
> 
> |  let till = time::get_time().sec as u64;
>   for rec in try! (expiration_idx.keyrange_to (&till)) {
>     hashes_found.push (rec.get_value::<u64>());}
> |


Will look into it. Does it happen with any data or there is a specific
data set?

**Comment by ArtemGr** [comment]
Happened half the time in a unit test which puts a `time::get_time().sec + X` and `time::get_time().sec` there. Might also encounter a `time::get_time().sec - Y` key from a previous run from time to time.

**Comment by vhbit** [comment]
If you have a unit test - can you provide its full source, it'll be much faster then.

**Comment by ArtemGr** [comment]
It's not an isolated test case. I might do one later.

**Comment by vhbit** [comment]
Potential fix landed in b6624bee442cefd59b28853ae16a3e897f727b4e.

As you're on a different branch you might be interested in cherry-picking only that commit (or you can rebase your branch on top of latest changes).

**Comment by ArtemGr** [comment]
Confirming, the fix works. Kudos!
